name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Build
      run: cargo build --verbose

    - name: Format
      run: cargo fmt --all -- --check

    - name: Lint
      continue-on-error: true # temporary
      run: cargo clippy --all-targets --all-features